spring:
  datasource:
   url: jdbc:mysql://101.132.37.234:3306/ssm?serverTimezone=GMT
   driver-class-name: com.mysql.cj.jdbc.Driver
   username: root
   password: root

  redis:
      jedis:
        pool:
          min-idle: 5
          max-active: 8
          max-idle: 8
          max-wait: 3000
      port: 6379
      host: localhost
      password:
      timeout: 3000
  cache:
      cache-names: redisCache
      redis:
        cache-null-values: false
        key-prefix:
        time-to-live:
        use-key-prefix: true
      type: redis