server:
  tomcat:
    uri-encoding: UTF-8
    min-spare-threads: 20
    max-threads: 100
    max-http-post-size: -1
  port: 8080
  connection-timeout: 3000
  servlet:
    context-path: /

spring:
  profiles:
    active: dev

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.tiantian.entity
  mapper-locations: classpath:com/tiantian/mapper/*.xml

